### ISSUE TITLE
Build failed dev.hilla.push.PushMessageHandler declares multiple scope

### ISSUE THREAD

**Issue by leotu** [mcollovati/quarkus-hilla#292] opened 2023-10-05 07:47 UTC
quarkus: 3.2.4.Final
hilla version 2.1.7
quarkus-hilla  version 2.0.1
Java SE 17.0.4.1

```java
[INFO] ------------------------------------------------------------------------
[INFO]  BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.019 s
[INFO] Finished at: 2023-10-04T15:32:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal mio.quarkus.platform:quarkus-maven-plugin:3.2.4.Final:build (default) on project [xxx-hilla: 
 Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Bean class dev.hilla.push.PushMessageHandler declares multiple scope type annotations: jakarta.enterprise.context.ApplicationScoped, jakarta.inject.Singleton
[ERROR]     at io.quarkus.arc.processor.Beans.multipleScopesFound(Beans.java:318)
[ERROR]     at io.quarkus.arc.processor.Beans$ClassBeanFactory.create(Beans.java:1277)
[ERROR]     at io.quarkus.arc.processor.Beans.createClassBean(Beans.java:52)
[ERROR]     at io.quarkus.arc.processor.BeanDeployment.findBeans(BeanDeployment.java:1161)
[ERROR]     at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:271)
[ERROR]     at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:141)
[ERROR]     at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:419)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]     at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
[ERROR]     at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]     at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]     at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]     at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

```

**Comment by mcollovati** [comment] 2023-10-05 08:47
Hi @leotu, thanks for trying out the extension and for filling the issue.

I tried locally, downloading a new app from code.quarkus.io and also with the [quarkus-hilla-starter](https://github.com/mcollovati/quarkus-hilla-starter) using the versions you mentioned, but I had no build errors.

Do you have any spring related extensions in your project?
Could you share an example project that reproduces the issue?

**Comment by leotu** [comment] 2023-10-06 01:45
I think the problem may arise from a conflict with the extension "quarkus-spring-data-jpa"


Download from: https://code.quarkus.io/?e=com.github.mcollovati%3Aquarkus-hilla
Import into Eclipse and pom.xml file just add 

```xml
 <dependency>
   <groupId>io.quarkus</groupId> 
   <artifactId>quarkus-spring-data-jpa</artifactId>
</dependency>
```
[code-with-quarkus_build-failed.zip](https://github.com/mcollovati/quarkus-hilla/files/12826158/code-with-quarkus_build-failed.zip)

**Comment by mcollovati** [comment] 2023-10-06 15:42
Unfortunately, the error is expected because the extension is not designed to work with Spring.

But you can use [Panache](https://quarkus.io/guides/hibernate-orm-panache) as a replacement for Spring Data JPA.
Here's a simple ToDo List [example](https://github.com/mcollovati/quarkus-hilla-todo-example) project using quarkus-hilla and panache to access persisted data

**Comment by leotu** [comment] 2023-10-11 01:48
I tried removing "quarkus-spring-data-jpa" and adding "quarkus-spring-di"  still build failed with the same error

```xml
   <!--
   <dependency>
	  <groupId>io.quarkus</groupId>
	  <artifactId>quarkus-spring-data-jpa</artifactId> 
   </dependency> 
   --> 
   <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-spring-di</artifactId>
   </dependency>
```

**Comment by leotu** [comment] 2023-10-11 02:14
The  code of Hilla Project uses a lot of @Bean @Autowired @Component, so I think this extension should be able to not affect quarkus-spring-di.
At the same time, I found that Hilla Project only PushMessageHandler.java uses @Service (excluding test code), so it seems that this extension only needs to solve
".addBeanClasses(PushEndpoint.class, PushMessageHandler.class)" will do.

https://github.com/mcollovati/quarkus-hilla/blob/3643742b590d380be236e14ffd198721320eba97/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/QuarkusHillaExtensionProcessor.java#L155

---
- Hilla Project

<img width="1053" alt="Hilla Project" src="https://github.com/mcollovati/quarkus-hilla/assets/1053138/32f80c2d-3659-4775-a038-48a5c91bf0c6">

---
- Quarkus-hilla

<img width="1064" alt="Quarkus-hilla" src="https://github.com/mcollovati/quarkus-hilla/assets/1053138/a7588e55-1222-485a-a2a8-d5a9e9e19809">

**Comment by mcollovati** [comment] 2023-10-11 05:38
@leotu thanks for investigation!
The whole point about the extension was running Hilla in a Quarkus environment without Spring, so we did not plant to support any of the `quarkus-spring-xxx` extensions.

For this reason, for example we have a dependency that shades the minimum amount of Spring classes required to make the build work, but we rely on the Quarkus Dependency Injection mechanism.

There are a couple of actions we can consider addressing this issue, such as remove the `@Service` annotation from `PushMessageHandler` or register the `PushMessageHandler` bean only if it is not already present.

Anyway, a full support for `quarkus-spring` is currently not planned because out of the scope of the extension, but we may consider it for the future, if there will be interest on it.

Out of curiosity and to better understand your use case, do you mind sharing the reasons for you to use Spring with Quarkus instead of the built-in DI or other suggested extension (e.g. Panache)?

**Closed** 2023-11-10 14:48 UTC
Labels: enhancement
